// Consulting Brief Generator — Data Templates
// Each domain contains arrays of randomizable components used to assemble unique briefs.

const DOMAINS = {
  marketing: {
    label: "Marketing",
    icon: "📣",
    color: "#e74c3c",
    clients: [
      { type: "D2C e-commerce startup", industry: "Fashion & Apparel", size: "20 employees", revenue: "$1.2M ARR" },
      { type: "Regional FMCG company", industry: "Food & Beverages", size: "250 employees", revenue: "$18M annual revenue" },
      { type: "SaaS company", industry: "HR Tech", size: "60 employees", revenue: "$4M ARR" },
      { type: "Luxury skincare brand", industry: "Beauty & Wellness", size: "40 employees", revenue: "$8M annual revenue" },
      { type: "Local restaurant chain", industry: "Food & Hospitality", size: "80 employees", revenue: "$5M annual revenue" },
      { type: "Consumer electronics brand", industry: "Technology", size: "120 employees", revenue: "$22M annual revenue" },
      { type: "Subscription box company", industry: "Retail", size: "35 employees", revenue: "$2.5M ARR" },
      { type: "Non-profit health organisation", industry: "Healthcare", size: "15 employees", revenue: "Grant-funded ($600K/year)" },
    ],
    challenges: [
      "Customer acquisition costs have risen 40% YoY while conversion rates remain flat.",
      "The brand lacks a consistent identity across digital channels, leading to low recall scores.",
      "Organic reach on social media has declined sharply following algorithm changes.",
      "The company is entering two new geographic markets and needs a go-to-market strategy.",
      "Existing customers are not being cross-sold or upsold effectively.",
      "The brand is perceived as outdated by the 18–30 age demographic.",
      "Competitors are aggressively spending on paid acquisition, eroding market share.",
      "Retention is poor — 60% of first-time customers never make a second purchase.",
    ],
    projects: [
      "Full-Funnel Digital Marketing Strategy",
      "Brand Repositioning & Identity Overhaul",
      "Customer Retention & Loyalty Programme Design",
      "Go-to-Market Strategy for New Market Entry",
      "Content Marketing & SEO Roadmap",
      "Influencer & Affiliate Marketing Programme",
      "Omnichannel Campaign Design",
      "Marketing Attribution Model Development",
    ],
    deliverables: [
      ["Comprehensive marketing audit (current state analysis)", "12-month channel strategy with budget allocation", "3 creative campaign concepts with messaging frameworks", "KPI dashboard template and measurement plan"],
      ["Brand positioning statement and messaging architecture", "Competitor benchmarking report", "Visual identity guidelines (do's and don'ts)", "Social media playbook"],
      ["Customer segmentation analysis", "Loyalty programme structure and mechanics", "Email nurture sequence (6 touchpoints)", "Churn prediction model outline"],
      ["Market sizing and opportunity assessment", "Localisation strategy", "Launch campaign plan with phased rollout", "Pricing and positioning recommendation"],
      ["SEO audit and keyword strategy", "Content calendar (90 days)", "Editorial guidelines", "Backlink acquisition strategy"],
    ],
    constraints: [
      { budget: "£15,000–£25,000", timeline: "8 weeks" },
      { budget: "£8,000–£12,000", timeline: "6 weeks" },
      { budget: "£30,000–£50,000", timeline: "12 weeks" },
      { budget: "£20,000", timeline: "10 weeks" },
      { budget: "£5,000", timeline: "4 weeks" },
    ],
    audience: ["The CMO and Head of Growth", "The CEO and Founder", "The Marketing Director and Board", "The Digital Marketing team"],
  },

  hr: {
    label: "Human Resources",
    icon: "👥",
    color: "#9b59b6",
    clients: [
      { type: "Professional services firm", industry: "Consulting", size: "500 employees", revenue: "$80M annual revenue" },
      { type: "Manufacturing company", industry: "Automotive components", size: "1,200 employees", revenue: "$200M annual revenue" },
      { type: "Fast-growing tech scale-up", industry: "FinTech", size: "150 employees", revenue: "$20M ARR" },
      { type: "Retail chain", industry: "Grocery & Convenience", size: "3,000 employees (mostly part-time)", revenue: "$450M annual revenue" },
      { type: "University", industry: "Higher Education", size: "2,500 staff", revenue: "Public funded" },
      { type: "Healthcare provider", industry: "Private Healthcare", size: "800 employees", revenue: "$120M annual revenue" },
      { type: "Non-profit organisation", industry: "Social Services", size: "60 employees", revenue: "$4M annual budget" },
    ],
    challenges: [
      "Voluntary attrition has risen to 28% annually, significantly above the industry average of 15%.",
      "The company is scaling from 150 to 400 employees within 18 months and lacks scalable HR processes.",
      "Employee engagement scores have fallen to 45% after a poorly managed restructuring.",
      "There is no structured performance management framework — reviews are ad hoc and inconsistent.",
      "The organisation lacks a diversity, equity and inclusion (DEI) strategy and is facing reputational pressure.",
      "Remote and hybrid work has fragmented culture, and collaboration has declined measurably.",
      "Succession planning is non-existent; 40% of senior roles have no identified successor.",
      "The onboarding process takes too long and new hires reach productivity 3 months later than the benchmark.",
    ],
    projects: [
      "Employee Experience & Engagement Strategy",
      "Talent Acquisition & Employer Branding Overhaul",
      "Performance Management Framework Design",
      "DEI Strategy & Implementation Roadmap",
      "HR Process Automation & Systems Review",
      "Succession Planning & Leadership Pipeline",
      "Hybrid Work Policy & Culture Design",
      "Onboarding Programme Redesign",
    ],
    deliverables: [
      ["Employee engagement survey design and analysis", "Root cause analysis of attrition drivers", "12-month employee experience roadmap", "Quick-win initiatives (implementable within 30 days)"],
      ["Employer value proposition (EVP) document", "Candidate persona profiles", "Recruitment process mapping with SLA targets", "Employer brand content strategy"],
      ["Performance framework design (objectives, ratings, calibration)", "Manager training guide", "Implementation timeline", "Communication plan for rollout"],
      ["DEI baseline assessment", "3-year DEI roadmap with measurable targets", "Policy recommendations", "Training programme outline"],
      ["HR technology audit", "Requirements specification for HRIS upgrade", "Vendor shortlist with evaluation criteria", "Change management plan"],
    ],
    constraints: [
      { budget: "£20,000–£35,000", timeline: "10 weeks" },
      { budget: "£12,000–£18,000", timeline: "8 weeks" },
      { budget: "£40,000–£60,000", timeline: "14 weeks" },
      { budget: "£8,000", timeline: "6 weeks" },
      { budget: "£25,000", timeline: "12 weeks" },
    ],
    audience: ["The CHRO and People Leadership Team", "The CEO and Executive Committee", "The HR Director and Line Managers", "The Board People Committee"],
  },

  operations: {
    label: "Operations",
    icon: "⚙️",
    color: "#27ae60",
    clients: [
      { type: "E-commerce fulfilment company", industry: "Logistics", size: "400 employees", revenue: "$55M annual revenue" },
      { type: "Hospital network", industry: "Healthcare", size: "2,000 staff", revenue: "$300M annual revenue" },
      { type: "Food manufacturing company", industry: "FMCG", size: "600 employees", revenue: "$90M annual revenue" },
      { type: "Software development agency", industry: "Technology Services", size: "80 employees", revenue: "$12M annual revenue" },
      { type: "Airline catering company", industry: "Hospitality & Aviation", size: "350 employees", revenue: "$40M annual revenue" },
      { type: "Retailer", industry: "Fashion", size: "200 employees", revenue: "$35M annual revenue" },
      { type: "Insurance company", industry: "Financial Services", size: "1,500 employees", revenue: "$180M gross written premium" },
    ],
    challenges: [
      "Order fulfilment errors have increased to 4.5%, well above the 1% industry benchmark.",
      "Supply chain disruptions have caused 15 stockouts in the past quarter, leading to £2M in lost revenue.",
      "The average time to complete a customer service request is 5 days, compared to a competitor benchmark of 1.5 days.",
      "Operational costs have grown 25% faster than revenue over the past two years.",
      "The company relies on manual, spreadsheet-based processes that create errors and bottlenecks.",
      "Capacity planning is reactive, causing chronic over- and under-staffing.",
      "Waste in the production process exceeds 12%, against a target of 3%.",
      "There is no clear SLA framework, so priorities are unclear and firefighting is constant.",
    ],
    projects: [
      "End-to-End Process Optimisation",
      "Supply Chain Resilience Review",
      "Lean Operations Transformation",
      "Operational Cost Reduction Programme",
      "Capacity Planning & Resource Optimisation",
      "Digital Operations & Automation Roadmap",
      "SLA Framework & Service Design",
      "Operational Excellence Programme Design",
    ],
    deliverables: [
      ["As-is process maps for 5 core processes", "Root cause analysis of key bottlenecks", "Future-state process design", "Implementation roadmap with prioritised quick wins"],
      ["Supply chain risk assessment", "Supplier diversification strategy", "Inventory optimisation model", "Business continuity playbook"],
      ["Waste and inefficiency audit (8 wastes framework)", "Lean implementation plan", "KPI scorecard", "Training plan for front-line teams"],
      ["Cost base analysis", "Cost reduction opportunity prioritisation matrix", "Business case for top 3 initiatives", "Governance framework for cost discipline"],
      ["Demand forecasting model", "Capacity planning tool (Excel/spreadsheet)", "Staffing model", "Recommendations for scheduling software"],
    ],
    constraints: [
      { budget: "£25,000–£40,000", timeline: "10 weeks" },
      { budget: "£15,000–£22,000", timeline: "8 weeks" },
      { budget: "£50,000–£80,000", timeline: "16 weeks" },
      { budget: "£10,000", timeline: "6 weeks" },
      { budget: "£35,000", timeline: "12 weeks" },
    ],
    audience: ["The COO and Operations Leadership Team", "The CEO and Board", "Plant and Site Managers", "The Supply Chain Director"],
  },

  strategy: {
    label: "Strategy",
    icon: "♟️",
    color: "#2980b9",
    clients: [
      { type: "Regional bank", industry: "Financial Services", size: "3,500 employees", revenue: "$1.2B annual revenue" },
      { type: "Private equity–backed retailer", industry: "Home Improvement", size: "1,800 employees", revenue: "$320M annual revenue" },
      { type: "Pharmaceutical company", industry: "Life Sciences", size: "900 employees", revenue: "$150M annual revenue" },
      { type: "Telecommunications provider", industry: "Telecoms", size: "5,000 employees", revenue: "$800M annual revenue" },
      { type: "Media and publishing group", industry: "Media", size: "600 employees", revenue: "$95M annual revenue" },
      { type: "National charity", industry: "Third Sector", size: "200 employees", revenue: "$30M annual budget" },
      { type: "Government agency", industry: "Public Sector", size: "1,200 employees", revenue: "Government funded" },
    ],
    challenges: [
      "The company lacks a clear 3–5 year strategy and is operating reactively to market pressures.",
      "Two large competitors have entered the market, threatening a 20% revenue decline.",
      "The organisation is pursuing too many strategic initiatives simultaneously, diluting resources and focus.",
      "A potential acquisition target has been identified and the board needs a recommendation.",
      "The core business is declining and diversification into adjacent markets is being considered.",
      "The company has grown through acquisitions but lacks an integrated operating model.",
      "Digitalisation is disrupting the industry and the company's response strategy is unclear.",
      "Stakeholder pressure is mounting to develop a credible ESG strategy.",
    ],
    projects: [
      "Corporate Strategy Development (3-Year Plan)",
      "Competitive Response Strategy",
      "Strategic Portfolio Review & Prioritisation",
      "M&A Due Diligence & Integration Strategy",
      "Market Entry & Diversification Assessment",
      "Digital Transformation Strategy",
      "ESG Strategy & Sustainability Roadmap",
      "Operating Model Design",
    ],
    deliverables: [
      ["External environment analysis (PESTLE, Porter's Five Forces)", "Internal capability assessment", "3-year strategic plan with strategic pillars", "Resource allocation framework and implementation roadmap"],
      ["Competitor deep-dive profiles (3 competitors)", "Competitive positioning map", "Strategic options assessment", "Recommended response strategy with financial projections"],
      ["Initiative inventory and evaluation criteria", "Portfolio prioritisation matrix", "Resource reallocation recommendations", "Governance model for portfolio management"],
      ["Target company assessment (financials, market position, culture)", "Synergy identification", "Integration playbook", "Recommendation with risk-adjusted scenarios"],
      ["Market sizing for 3 adjacencies", "Attractiveness and fit assessment", "Entry mode options (build, buy, partner)", "Recommended strategy with go/no-go criteria"],
    ],
    constraints: [
      { budget: "£40,000–£70,000", timeline: "12 weeks" },
      { budget: "£25,000–£45,000", timeline: "10 weeks" },
      { budget: "£80,000–£120,000", timeline: "16 weeks" },
      { budget: "£15,000", timeline: "8 weeks" },
      { budget: "£55,000", timeline: "14 weeks" },
    ],
    audience: ["The CEO and Executive Leadership Team", "The Board of Directors", "The Strategy Director and C-Suite", "Investors and the Management Team"],
  },

  management: {
    label: "Management",
    icon: "🏛️",
    color: "#f39c12",
    clients: [
      { type: "Family-owned business", industry: "Construction", size: "120 employees", revenue: "$25M annual revenue" },
      { type: "Scale-up tech company", industry: "Marketplace Platform", size: "200 employees", revenue: "$30M ARR" },
      { type: "Professional services firm", industry: "Legal", size: "80 partners + 300 staff", revenue: "$60M annual revenue" },
      { type: "Local authority", industry: "Public Sector", size: "1,800 employees", revenue: "Government funded" },
      { type: "Private school", industry: "Education", size: "150 staff", revenue: "$15M annual revenue" },
      { type: "Healthcare clinic group", industry: "Healthcare", size: "250 employees", revenue: "$40M annual revenue" },
    ],
    challenges: [
      "The leadership team lacks alignment on strategic priorities, causing internal conflict and slow decision-making.",
      "Middle management has been promoted for technical expertise but lacks people management skills.",
      "The organisation has grown rapidly and its flat structure is now creating coordination problems.",
      "There is no consistent management rhythm — meetings are ad hoc and accountability is unclear.",
      "A new CEO has taken over and needs to assess the organisation and set direction.",
      "The board and management team have a dysfunctional relationship that is stalling progress.",
      "Key decisions are bottlenecked at the top because management is not empowered to act.",
      "The organisation is resistant to change, and past transformation attempts have failed.",
    ],
    projects: [
      "Leadership Effectiveness Assessment & Development Plan",
      "Organisational Design & Restructuring",
      "Management Capability Building Programme",
      "Governance & Decision-Making Framework",
      "New Leader Onboarding & First 100 Days Plan",
      "Change Management Programme",
      "Management Operating System Design",
      "Board Effectiveness Review",
    ],
    deliverables: [
      ["Leadership team assessment (interviews + 360 feedback)", "Capability gap analysis", "Individual development plans for each leader", "Team effectiveness roadmap"],
      ["Organisation design principles", "Current vs future-state org chart", "Role clarity framework (RACI)", "Implementation and communication plan"],
      ["Management skills audit", "Customised training curriculum (6 modules)", "Coaching programme design", "Manager toolkit"],
      ["Decision rights framework (RACI/DACI)", "Meeting cadence and governance design", "Accountability framework", "Communication cascade plan"],
      ["Stakeholder mapping and engagement plan", "100-day priority agenda", "Key decisions to make in first 90 days", "Communication strategy"],
    ],
    constraints: [
      { budget: "£20,000–£35,000", timeline: "10 weeks" },
      { budget: "£12,000–£20,000", timeline: "8 weeks" },
      { budget: "£45,000–£65,000", timeline: "14 weeks" },
      { budget: "£8,000", timeline: "6 weeks" },
      { budget: "£30,000", timeline: "12 weeks" },
    ],
    audience: ["The CEO and Executive Team", "The Chairman and Board", "The HR Director and Senior Leadership", "All people managers"],
  },

  finance: {
    label: "Finance",
    icon: "💰",
    color: "#16a085",
    clients: [
      { type: "Manufacturing company", industry: "Industrial Equipment", size: "700 employees", revenue: "$110M annual revenue" },
      { type: "Early-stage startup", industry: "CleanTech", size: "25 employees", revenue: "Pre-revenue (Seed funded)" },
      { type: "Private equity portfolio company", industry: "Business Services", size: "400 employees", revenue: "$60M annual revenue" },
      { type: "Family office", industry: "Investment Management", size: "12 employees", revenue: "$500M AUM" },
      { type: "Mid-market retailer", industry: "Sports & Outdoors", size: "500 employees", revenue: "$75M annual revenue" },
      { type: "Property development company", industry: "Real Estate", size: "80 employees", revenue: "$90M annual revenue" },
      { type: "SaaS company", industry: "Legal Tech", size: "110 employees", revenue: "$12M ARR" },
    ],
    challenges: [
      "Cash flow is chronically tight — the company has less than 6 weeks of runway despite being profitable on paper.",
      "The finance function is transactional and does not provide strategic insight to business leaders.",
      "The company is preparing for a Series B fundraise and needs investor-ready financial materials.",
      "Working capital is poorly managed — debtor days are 75 vs an industry norm of 30.",
      "The company has no formal budgeting or forecasting process; decisions are made without financial rigour.",
      "A potential exit (trade sale or IPO) is planned in 3 years and financial readiness is poor.",
      "Margins have compressed by 8 percentage points and the underlying drivers are unclear.",
      "The company is over-leveraged following an acquisition and needs a deleveraging strategy.",
    ],
    projects: [
      "Cash Flow Management & Working Capital Optimisation",
      "Finance Function Transformation",
      "Fundraise Preparation & Investor Readiness",
      "Budgeting & Forecasting Process Design",
      "Margin Improvement & Profitability Analysis",
      "Exit Readiness Programme",
      "Financial Modelling & Business Case Development",
      "Treasury & Capital Structure Review",
    ],
    deliverables: [
      ["13-week cash flow forecast model", "Working capital optimisation recommendations", "Cash conversion cycle analysis", "Quick-win action plan (30 days)"],
      ["Finance function maturity assessment", "Target operating model for finance", "Technology and tools recommendation (ERP/FP&A)", "Implementation roadmap"],
      ["Financial model (3-statement, 5-year)", "Investor deck (12–15 slides)", "Data room structure and content checklist", "Due diligence preparation guide"],
      ["Budget process design", "Rolling forecast model", "KPI and management accounts template", "Finance calendar and governance"],
      ["P&L waterfall analysis", "Product/segment profitability model", "Cost driver analysis", "Recommendations with financial impact quantification"],
    ],
    constraints: [
      { budget: "£20,000–£35,000", timeline: "8 weeks" },
      { budget: "£10,000–£18,000", timeline: "6 weeks" },
      { budget: "£40,000–£65,000", timeline: "12 weeks" },
      { budget: "£8,000", timeline: "5 weeks" },
      { budget: "£50,000", timeline: "14 weeks" },
    ],
    audience: ["The CFO and Finance Leadership Team", "The CEO and Board", "The FD and Management Team", "Private Equity Owners and Investors"],
  },

  banking: {
    label: "Banking & Financial Services",
    icon: "🏦",
    color: "#2c3e50",
    clients: [
      { type: "Regional commercial bank", industry: "Banking", size: "4,000 employees", revenue: "$600M net interest income" },
      { type: "Digital challenger bank", industry: "FinTech/Banking", size: "180 employees", revenue: "$25M ARR" },
      { type: "Wealth management firm", industry: "Asset Management", size: "300 employees", revenue: "$45M annual revenue" },
      { type: "Insurance company", industry: "General Insurance", size: "1,200 employees", revenue: "$350M gross written premium" },
      { type: "Payments processor", industry: "Financial Infrastructure", size: "250 employees", revenue: "$80M annual revenue" },
      { type: "Credit union", industry: "Mutual Finance", size: "60 employees", revenue: "$8M annual revenue" },
      { type: "Investment bank (boutique)", industry: "Capital Markets", size: "90 professionals", revenue: "$30M fee revenue" },
    ],
    challenges: [
      "Net interest margin is under pressure as competition for deposits intensifies.",
      "The bank's digital offering lags behind challenger banks and customer satisfaction is declining.",
      "Credit risk management processes are manual and prone to errors, creating regulatory exposure.",
      "The cost-to-income ratio has risen to 72%, well above the target of 55%.",
      "Anti-money laundering (AML) compliance processes are inefficient and costly.",
      "The institution is facing new regulatory requirements (e.g. Basel IV, Consumer Duty) and readiness is low.",
      "Cross-selling of financial products to existing customers is below potential.",
      "The branch network is loss-making but there is significant political and reputational risk to closures.",
    ],
    projects: [
      "Digital Banking Strategy & Roadmap",
      "Credit Risk Framework Review",
      "Cost Efficiency & Operating Model Redesign",
      "Regulatory Compliance Readiness Assessment",
      "Customer Propositions & Product Strategy",
      "Branch Network Rationalisation Strategy",
      "Payments Modernisation Strategy",
      "AML & Financial Crime Risk Review",
    ],
    deliverables: [
      ["Digital maturity benchmarking", "Customer journey maps (3 key journeys)", "Digital product roadmap (18 months)", "Technology architecture recommendations"],
      ["Credit risk policy review", "Scorecard model assessment", "Exceptions and overrides analysis", "Recommendations and implementation plan"],
      ["Cost base analysis by business unit", "Benchmarking vs peer group", "Cost reduction opportunities (ranked by impact and feasibility)", "Business case for top 3 initiatives"],
      ["Gap analysis against regulatory requirements", "Risk-rated action plan", "Governance and accountability framework", "Board reporting template"],
      ["Customer needs research synthesis", "Product portfolio assessment", "Pricing strategy review", "New product concepts with business cases"],
    ],
    constraints: [
      { budget: "£45,000–£75,000", timeline: "12 weeks" },
      { budget: "£25,000–£40,000", timeline: "10 weeks" },
      { budget: "£80,000–£130,000", timeline: "16 weeks" },
      { budget: "£15,000", timeline: "8 weeks" },
      { budget: "£60,000", timeline: "14 weeks" },
    ],
    audience: ["The CEO and Executive Committee", "The Board Risk Committee", "The COO and Transformation team", "The CRO and Compliance Leadership"],
  },

  technology: {
    label: "Technology & Digital",
    icon: "💻",
    color: "#8e44ad",
    clients: [
      { type: "Legacy enterprise software company", industry: "B2B Software", size: "800 employees", revenue: "$120M annual revenue" },
      { type: "Retailer", industry: "Grocery", size: "5,000 employees", revenue: "$900M annual revenue" },
      { type: "Media company", industry: "Broadcasting", size: "1,200 employees", revenue: "$200M annual revenue" },
      { type: "Logistics company", industry: "Last-Mile Delivery", size: "600 employees", revenue: "$85M annual revenue" },
      { type: "Healthcare provider", industry: "Primary Care", size: "400 staff", revenue: "NHS-commissioned" },
      { type: "Professional services firm", industry: "Accountancy", size: "500 employees", revenue: "$70M annual revenue" },
    ],
    challenges: [
      "The company's core technology platform is a 15-year-old monolith that is expensive to maintain and slow to change.",
      "Data is siloed across 12 different systems, making reporting and analytics unreliable.",
      "Cybersecurity posture is weak — a recent audit flagged 35 high-risk vulnerabilities.",
      "The company is spending 80% of its IT budget on running existing systems, leaving nothing for innovation.",
      "AI/ML adoption is ad hoc and ungoverned, creating quality and risk concerns.",
      "The technology organisation is not aligned to business priorities and is seen as a cost centre.",
      "Cloud migration is stalled at 30% and is running 18 months behind schedule.",
      "The company lacks a data governance framework, creating compliance and quality issues.",
    ],
    projects: [
      "Technology Strategy & Modernisation Roadmap",
      "Data Strategy & Analytics Transformation",
      "Cybersecurity Maturity Assessment & Remediation Plan",
      "IT Operating Model Redesign",
      "AI/ML Strategy & Governance Framework",
      "Cloud Migration Strategy",
      "Digital Product Strategy",
      "Data Governance Framework Design",
    ],
    deliverables: [
      ["Technology landscape assessment", "Architecture principles and target state", "Modernisation roadmap (3 years)", "Investment and resource plan"],
      ["Data maturity assessment", "Data architecture blueprint", "Analytics use case prioritisation", "Data team structure and hiring plan"],
      ["Cybersecurity risk assessment (ISO 27001/NIST)", "Vulnerability prioritisation matrix", "Remediation roadmap", "Security governance framework"],
      ["IT organisation design", "ITIL/DevOps operating model", "Vendor management strategy", "Internal vs outsource recommendation"],
      ["AI use case identification and prioritisation", "AI governance framework", "Build vs buy vs partner analysis", "Pilot programme design"],
    ],
    constraints: [
      { budget: "£35,000–£60,000", timeline: "12 weeks" },
      { budget: "£20,000–£35,000", timeline: "10 weeks" },
      { budget: "£70,000–£110,000", timeline: "16 weeks" },
      { budget: "£12,000", timeline: "8 weeks" },
      { budget: "£45,000", timeline: "14 weeks" },
    ],
    audience: ["The CTO/CIO and Technology Leadership", "The CEO and Board", "The Digital Transformation Director", "IT and Business stakeholders"],
  },

  sustainability: {
    label: "Sustainability & ESG",
    icon: "🌱",
    color: "#229954",
    clients: [
      { type: "FTSE 250 consumer goods company", industry: "Household Products", size: "2,500 employees", revenue: "$400M annual revenue" },
      { type: "Housebuilder", industry: "Real Estate & Construction", size: "600 employees", revenue: "$150M annual revenue" },
      { type: "Global logistics company", industry: "Shipping & Freight", size: "8,000 employees", revenue: "$1.5B annual revenue" },
      { type: "Pension fund", industry: "Asset Management", size: "80 employees", revenue: "$2B AUM" },
      { type: "Food manufacturer", industry: "FMCG", size: "900 employees", revenue: "$180M annual revenue" },
      { type: "University", industry: "Higher Education", size: "3,000 staff", revenue: "£250M annual income" },
    ],
    challenges: [
      "The company has made net-zero pledges but has no credible pathway to deliver on them.",
      "Investors are demanding ESG reporting aligned to TCFD/CSRD and the company is not ready.",
      "Supply chain emissions (Scope 3) are unknown and unmanaged.",
      "The company faces growing regulatory pressure on plastic packaging and has no transition plan.",
      "ESG is seen as a marketing function rather than embedded in business decision-making.",
      "The company wants to launch a green finance product but lacks the credentials and governance.",
      "Employee pressure to improve the company's environmental performance is growing.",
      "The board lacks ESG expertise and governance structures are inadequate.",
    ],
    projects: [
      "Net Zero Strategy & Decarbonisation Roadmap",
      "ESG Reporting Framework Design",
      "Scope 3 Emissions Assessment & Strategy",
      "Sustainable Supply Chain Programme",
      "ESG Governance & Board Capability",
      "Green Product Strategy",
      "Climate Risk Assessment (TCFD)",
      "Social Impact Measurement Framework",
    ],
    deliverables: [
      ["Baseline carbon footprint (Scope 1, 2, 3)", "Science-based targets setting", "Decarbonisation initiatives portfolio", "Net zero roadmap with milestones and investment required"],
      ["ESG materiality assessment", "Reporting framework alignment (GRI, SASB, TCFD, CSRD)", "Data collection and reporting process design", "Draft ESG report outline"],
      ["Scope 3 emissions inventory", "Supplier engagement strategy", "Hotspot analysis and reduction priorities", "Supplier code of conduct"],
      ["Supply chain sustainability risk assessment", "Supplier sustainability scorecard", "Sustainable sourcing policy", "Engagement and capacity building plan"],
      ["ESG governance gap analysis", "Board and committee structure recommendations", "ESG training programme for directors", "ESG metrics for executive remuneration"],
    ],
    constraints: [
      { budget: "£30,000–£50,000", timeline: "12 weeks" },
      { budget: "£15,000–£25,000", timeline: "8 weeks" },
      { budget: "£60,000–£90,000", timeline: "16 weeks" },
      { budget: "£10,000", timeline: "6 weeks" },
      { budget: "£40,000", timeline: "14 weeks" },
    ],
    audience: ["The CEO and Sustainability Director", "The Board and Audit/Risk Committee", "The CFO and Investor Relations team", "The Chief Sustainability Officer"],
  },
};

// Utility: pick a random item from an array
function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Utility: pick a random integer between min and max (inclusive)
function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

// Generate a unique brief for a given domain key (or random if null)
function generateBrief(domainKey) {
  const key = domainKey || pick(Object.keys(DOMAINS));
  const domain = DOMAINS[key];

  const client = pick(domain.clients);
  const challenge = pick(domain.challenges);
  const project = pick(domain.projects);
  const deliverables = pick(domain.deliverables);
  const constraint = pick(domain.constraints);
  const audience = pick(domain.audience);

  // Generate a pseudo-random project ID
  const id = `${key.toUpperCase().slice(0, 3)}-${Date.now().toString(36).toUpperCase().slice(-5)}`;

  return {
    id,
    domainKey: key,
    domainLabel: domain.label,
    domainIcon: domain.icon,
    domainColor: domain.color,
    client,
    challenge,
    project,
    deliverables,
    constraint,
    audience,
  };
}
